name: Run CI Tests
env:
  GOTOOLCHAIN: go1.23.2
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  push:
    branches:
      - 'main'
jobs:
  run-copywrite:
    timeout-minutes: 5
    runs-on: vm-alpine-3
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-copywrite@v1.1.3
      - name: verify copyright
        run: |
          copywrite --config .github/workflows/scripts/copywrite.hcl \
            headers --spdx "BSD-3-Clause" --plan
  run-lint:
    timeout-minutes: 5
    runs-on: m2-macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          args: --config .github/workflows/scripts/golangci.yaml
  run-tests:
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os:
          # - vm-freebsd-14
          # - vm-alpine-3
          - m2-macos-14
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: ${{ contains(runner.name, 'Github Actions') }}
          go-version-file: go.mod
          cache-dependency-path: '**/go.sum'
      - name: Run Go Test
        run: |
          just test

