name: Run CI Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  push:
    branches:
      - 'main'
jobs:
  run-tests:
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b
      - name: Install memcached
        run: |
          os=$(uname)
          case $os in
            Linux)
              sudo apt-get update && sudo apt-get install -y memcached
              ;;
            Darwin)
              brew install memcached
              ;;
            *)
              exit 3
              ;;
          esac
      - name: Run Go Test
        run: |
          just init tidy lint tests
