name: Run CI Tests
env:
  GOTOOLCHAIN: go1.23.4
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  push:
    branches:
      - 'main'
jobs:
  run-copywrite:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-copywrite@v1.1.3
      - name: verify copyright
        run: |
          copywrite --config .github/workflows/scripts/copywrite.hcl \
            headers --spdx "BSD-3-Clause" --plan
  run-lint:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.2
          args: --config .github/workflows/scripts/golangci.yaml
  run-tests:
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: ${{ contains(runner.name, 'Github Actions') }}
          go-version-file: go.mod
          cache-dependency-path: '**/go.sum'
      - uses: extractions/setup-just@v2
      - name: Install memcached
        run:
          sudo apt-get update && sudo apt-get install -y memcached
      - name: Run Go Test
        run: |
          just test
