name: Run CI Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  push:
    branches:
      - 'main'
jobs:
  run-copywrite:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-copywrite@v1.1.3
      - name: verify copyright
        run: |
          copywrite --config .github/workflows/scripts/copywrite.hcl \
            headers --spdx "BSD-3-Clause" --plan
  run-tests:
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: extractions/setup-just@v3
      - name: Install memcached
        run: |
          os=$(uname)
          case $os in
            Linux)
              sudo apt-get update && sudo apt-get install -y memcached
              ;;
            Darwin)
              brew install memcached
              ;;
            *)
              exit 3
              ;;
          esac
      - name: Run Go Test
        run: |
          just init tidy lint tests
